"""
experiments/temporal_test.py
Temporal CNDP experiment: simulate T evolving graph snapshots.

Snapshots are generated by rewiring a fraction of edges each timestep,
simulating a drifting network (social network churn, power-grid updates, etc.)

Usage:
    python -m experiments.temporal_test --n 5000 --T 10 --k 15 --rewire 0.05
"""

import argparse
import json
import logging
import os
import random
import sys
import time

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from cndp.graph import generate_barabasi_albert, LargeGraph
from cndp.temporal import TemporalGraphManager
from cndp.greedy import lazy_greedy_cndp
from cndp.centrality import compute_all_centralities
from cndp.scoring import score_nodes
from cndp.metrics import lcc_size
from cndp.utils import setup_logging
from cndp.cascade import simulate_si_cascade

logger = logging.getLogger(__name__)

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
PLOTS_DIR   = os.path.join(RESULTS_DIR, "plots")
LOGS_DIR    = os.path.join(RESULTS_DIR, "logs")
os.makedirs(PLOTS_DIR, exist_ok=True)
os.makedirs(LOGS_DIR,  exist_ok=True)


# ─────────────────────────────────────────────────────────────────────────────
#  Snapshot generator: random edge rewiring
# ─────────────────────────────────────────────────────────────────────────────

def rewire_graph(G_base: LargeGraph, rewire_frac: float, rng: random.Random) -> LargeGraph:
    """
    Produce a new snapshot by randomly rewiring `rewire_frac` of edges.
    """
    G = G_base.copy()
    all_edges  = list(G.edges())
    all_nodes  = G.nodes()
    n_rewire   = max(1, int(len(all_edges) * rewire_frac))
    to_rewire  = rng.sample(all_edges, min(n_rewire, len(all_edges)))

    for u, v in to_rewire:
        G.remove_edge(u, v)
        # add a random new edge
        attempts = 0
        while attempts < 10:
            a = rng.choice(all_nodes)
            b = rng.choice(all_nodes)
            if a != b and G.has_node(a) and G.has_node(b):
                G.add_edge(a, b)
                break
            attempts += 1

    return G


# ─────────────────────────────────────────────────────────────────────────────
#  Main temporal experiment
# ─────────────────────────────────────────────────────────────────────────────

def run_temporal_experiment(
    n: int,
    T: int,
    k: int,
    rewire_frac: float,
    ewma_alpha: float,
    betweenness_k: int,
    seed: int = 42,
):
    rng = random.Random(seed)
    np.random.seed(seed)

    logger.info(f"Temporal CNDP: n={n}, T={T}, k={k}, rewire={rewire_frac}, α={ewma_alpha}")

    # ── Initial snapshot ──────────────────────────────────────────────────────
    G0 = generate_barabasi_albert(n, m=3, seed=seed)

    # ── Temporal manager ──────────────────────────────────────────────────────
    mgr = TemporalGraphManager(
        ewma_alpha    = ewma_alpha,
        betweenness_k = betweenness_k,
    )

    snapshots   = [G0]
    G_current   = G0
    for _ in range(T - 1):
        G_current = rewire_graph(G_current, rewire_frac, rng)
        snapshots.append(G_current)

    # ── Per-snapshot results ──────────────────────────────────────────────────
    smoothness_history   = []
    lcc_temporal_history = []   # LCC after temporal-guided removal
    lcc_static_history   = []   # LCC after static degree removal (baseline)
    inf_temporal_history = []   # Infection spread after temporal removal
    inf_static_history   = []   # Infection spread after static removal

    for t, G_t in enumerate(snapshots):
        logger.info(f"--- Snapshot t={t} ---")

        # 1. Temporal scores
        snap_result = mgr.process_snapshot(G_t, k=k, seed=seed + t)
        smoothness_history.append(snap_result["smoothness_penalty"])

        # 2. Remove temporal-selected nodes and measure metrics
        G_tmp = G_t.copy()
        for v in snap_result["selected"]:
            if G_tmp.has_node(v):
                G_tmp.remove_node(v)
        lcc_temporal_history.append(lcc_size(G_tmp))
        
        inf_temp = simulate_si_cascade(G_t, snap_result["selected"], seed=seed + t)
        inf_temporal_history.append(inf_temp)

        # 3. Static degree baseline
        G_tmp2 = G_t.copy()
        top_degree = sorted(G_t.nodes(), key=lambda v: G_t.degree(v), reverse=True)[:k]
        for v in top_degree:
            if G_tmp2.has_node(v):
                G_tmp2.remove_node(v)
        lcc_static_history.append(lcc_size(G_tmp2))
        
        inf_stat = simulate_si_cascade(G_t, top_degree, seed=seed + t)
        inf_static_history.append(inf_stat)

        logger.info(
            f"  temporal LCC={lcc_temporal_history[-1]} (Inf: {inf_temp:.2%})  "
            f"static LCC={lcc_static_history[-1]} (Inf: {inf_stat:.2%})  "
            f"smoothness={smoothness_history[-1]:.4f}"
        )

    # ── Save + Plot ───────────────────────────────────────────────────────────
    records = {
        "n": n, "T": T, "k": k, "rewire_frac": rewire_frac, "ewma_alpha": ewma_alpha,
        "smoothness_history"   : smoothness_history,
        "lcc_temporal_history" : lcc_temporal_history,
        "lcc_static_history"   : lcc_static_history,
        "inf_temporal_history" : inf_temporal_history,
        "inf_static_history"   : inf_static_history,
    }
    json_path = os.path.join(LOGS_DIR, f"temporal_n{n}_T{T}.json")
    with open(json_path, "w") as fh:
        json.dump(records, fh, indent=2)
    logger.info(f"Temporal results → {json_path}")

    _plot_temporal_lcc(lcc_temporal_history, lcc_static_history, inf_temporal_history, inf_static_history, smoothness_history, n, T)
    return records


# ─────────────────────────────────────────────────────────────────────────────
#  Plots
# ─────────────────────────────────────────────────────────────────────────────

def _plot_temporal_lcc(temporal_lcc, static_lcc, temporal_inf, static_inf, smoothness, n, T):
    ts = list(range(T))
    fig, (ax1, ax2, ax3) = plt.subplots(3, 1, figsize=(10, 12), sharex=True)

    ax1.plot(ts, temporal_lcc, "o-", color="#E63946", lw=2, label="Temporal CNDP")
    ax1.plot(ts, static_lcc,   "s-", color="#457B9D", lw=2, label="Static Degree")
    ax1.set_ylabel("LCC Size", fontsize=12)
    ax1.set_title(f"Temporal CNDP LCC Reduction — n={n:,}", fontsize=14)
    ax1.legend(fontsize=11)
    ax1.grid(True, alpha=0.3)
    
    ax2.plot(ts, temporal_inf, "o-", color="#E76F51", lw=2, label="Temporal CNDP Infection")
    ax2.plot(ts, static_inf,   "s-", color="#264653", lw=2, label="Static Degree Infection")
    ax2.set_ylabel("Infection Spread Ratio", fontsize=12)
    ax2.set_title("Information/Epidemic Cascade Resilience", fontsize=13)
    ax2.legend(fontsize=11)
    ax2.grid(True, alpha=0.3)

    ax3.bar(ts, smoothness, color="#2A9D8F", alpha=0.7)
    ax3.set_xlabel("Snapshot (t)", fontsize=12)
    ax3.set_ylabel("Smoothness Penalty", fontsize=12)
    ax3.set_title("Temporal Stability", fontsize=13)
    ax3.grid(True, alpha=0.3)

    plt.tight_layout()
    path = os.path.join(PLOTS_DIR, f"temporal_n{n}_T{T}.png")
    plt.savefig(path, dpi=150)
    plt.close()
    logger.info(f"Temporal plot → {path}")


# ─────────────────────────────────────────────────────────────────────────────
#  CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(description="Temporal CNDP Experiment")
    p.add_argument("--n",      type=int,   default=5_000,  help="Nodes in initial graph")
    p.add_argument("--T",      type=int,   default=10,     help="Number of snapshots")
    p.add_argument("--k",      type=int,   default=15,     help="Nodes removed per snapshot")
    p.add_argument("--rewire", type=float, default=0.05,   help="Edge rewiring fraction per step")
    p.add_argument("--alpha",  type=float, default=0.5,    help="EWMA smoothing factor")
    p.add_argument("--bet_k",  type=int,   default=100,    help="Betweenness sample size")
    p.add_argument("--seed",   type=int,   default=42)
    p.add_argument("--log_level", default="INFO")
    return p.parse_args()


if __name__ == "__main__":
    args = parse_args()
    setup_logging(
        level=args.log_level,
        log_file=os.path.join(LOGS_DIR, "temporal_test.log"),
    )
    run_temporal_experiment(
        n            = args.n,
        T            = args.T,
        k            = args.k,
        rewire_frac  = args.rewire,
        ewma_alpha   = args.alpha,
        betweenness_k= args.bet_k,
        seed         = args.seed,
    )
